name: 'Create release'
description: 'Creating new branch and release issue'
outputs:
  issueNumber:
    description: "Release issue number"
    value: ${{ steps.createIssue.outputs.number }}
  issueLink:
    description: "Release issue link"
    value: ${{ steps.createIssue.outputs.url }}
  changelog:
    description: "Changelog"
    value: ${{ steps.create_changelog.outputs.changelog }}
runs:
  using: 'composite'
  steps:
    - name: Create branch
      uses: ./.github/actions/create-branch
      with:
        commitSHA: ${{ github.sha }}
        releaseTag: ${{ github.ref_name }}
        token: ${{ github.token }}
    - name: Create CHANGELOG
      id: create_changelog
      uses: ./.github/actions/create-changelog
    - name: Create release issue
      id: createIssue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TAG: ${{ github.ref_name }}
        CHANGELOG: ${{ steps.create_changelog.outputs.changelog }}
        LABELS: "release-candidate"
      with:
        update_existing: true
        search_existing: all
        filename: .github/actions/create-release/ISSUE_TEMPLATE.md