name: 'Run tests'
description: 'Run lint && e2e && unit test'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: v16.19.0
        cache: npm
    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
    - run: npm ci
      shell: bash
    - name: Run linters
      run: npm run lint
      shell: bash
    - run: npx playwright install --with-deps
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - name: Run tests
      run: npm run test-ci
      shell: bash
    - name: Run e2e tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm run e2e-ci
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30  