name: 'Run tests'
description: 'Run lint && e2e && unit test'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: v16.19.0
        cache: npm
    - run: npm ci
      shell: bash
    - name: Run linters
      run: npm run lint
      shell: bash
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    - name: Run tests
      run: npm run test-ci
      shell: bash
    # - name: Run e2e tests
    #   uses: coactions/setup-xvfb@v1
    #   with:
    #     run: npm run e2e-ci
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30  