name: Deploy specific release
run-name: Deploy to pages

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run ci && npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build