name: Check conventional commits
run-name: Check commit for conventional naming
on: [push]
jobs:
  Check-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
        with:
          commitDepth: 1