name: Push action
run-name: Testing ${{ github.actor }} push
on: [push]
jobs:
  Testing-Commit-Message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
