name: Create release candidate
run-name: Release ${{ github.ref_name }} version
on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  Create-Release- Candidate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/create-release.yml