name: Release
run-name: Release {{ github.ref_name }} version
on:
  push:
    tags:
      - 'v[0-9]+'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print versions
        run: |
          echo ${{ github.sha }}
          echo ${{ github.ref_name }}
