name: Release
run-name: Release ${{ github.ref_name }} version
on:
  push:
    tags:
      - 'v[0-9]+'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate changelog
        uses: actions/github-script@v6
        id: changelog
        env:
          SHA: ${{ github.sha }}
          TAG: ${{ github.ref_name }}
        with:
          result-encoding: string
          script: |
            const script = require('./scripts/getChangelog.js')
      - name: Print CHANGELOG
        run: echo "${{steps.changelog.outputs.changelog}}"
